import { describe, it, expect } from 'vitest';
import fs from 'fs';
import path from 'path';
import os from 'os';
import { TitleService } from '../title-service';
import { DedupEngine } from '../dedup-engine';
import { VolumeWatcher } from '../volume-watcher';
import { AudioEngine } from '../audio-engine';
import { PipelineOrchestrator } from '../pipeline-orchestrator';
import { generateSyntheticWavBuffer } from '../../test/audio-fixture';

describe('Slice F10: Transcript Versions, Corrections & AI Ownership', () => {
  describe('TitleService Idempotence & Deduplication', () => {
    const titleService = new TitleService();

    it('extracts base filename cleanly and strips previous title suffixes', () => {
      expect(titleService.extractBaseFileName('ZOOM0001 - Harmony Warmups.WAV')).toBe('ZOOM0001');
      expect(titleService.extractBaseFileName('260831-185613 - Ideas.mp3')).toBe('260831-185613');
      expect(titleService.extractBaseFileName('TAKE_01')).toBe('TAKE_01');
    });

    it('generates composite title idempotently without repeating suffixes', async () => {
      // First generation
      const first = await titleService.generateCompositeTitle('ZOOM0001', 'talking about acoustic guitar chords and feelings');
      expect(first).toContain('ZOOM0001 - ');

      // Re-running generation on the already composite title should not repeat the base prefix or suffix
      const second = await titleService.generateCompositeTitle(first, 'talking about acoustic guitar chords and feelings');
      expect(second).toBe(first);

      // Suffix should not be duplicated
      const baseName = titleService.extractBaseFileName(first);
      expect(second.split(baseName).length - 1).toBe(1);
    });

    it('returns short title directly if base filename is identical to generated title', async () => {
      const res = await titleService.generateCompositeTitle('Guitar Chords', 'guitar chords guitar chords');
      expect(res).toBe('Guitar Chords');
    });
  });

  describe('DedupEngine Transcript Versions & Sidecars', () => {
    it('manages .edited.txt sidecar and maintains transcriptVersions array', () => {
      const sandboxVaultDir = fs.mkdtempSync(path.join(os.tmpdir(), 'f10-vault-'));
      try {
        const rawDir = path.join(sandboxVaultDir, 'raw');
        fs.mkdirSync(rawDir, { recursive: true });

        const rawFilePath = path.join(rawDir, 'TAKE_F10.WAV');
        fs.writeFileSync(rawFilePath, generateSyntheticWavBuffer({ durationSeconds: 1.0 }));

        const dedup = new DedupEngine(sandboxVaultDir);

        const rawRecord = {
          id: 'raw_f10',
          fingerprint: 'f10_fingerprint_abc',
          originalFilename: 'TAKE_F10.WAV',
          storagePath: rawFilePath,
          fileSizeBytes: 1000,
          durationSeconds: 1.0,
          sampleRate: 44100,
          channels: 1,
          sourceDevice: 'Test Mic',
          importedAt: new Date().toISOString(),
          waveformPeaks: [0.1, 0.4, 0.2],
        };
        dedup.addRawFile(rawRecord);

        // Machine Whisper transcript sidecar
        const txtPath = path.join(rawDir, 'TAKE_F10.txt');
        fs.writeFileSync(txtPath, 'Original machine transcript generated by Whisper.', 'utf-8');

        const clipRecord = {
          id: 'clip_f10',
          parentFileId: 'raw_f10',
          title: 'TAKE_F10 - Meeting Notes',
          startTimeSeconds: 0,
          endTimeSeconds: 1.0,
          category: 'dictaphone' as const,
          userTags: [],
          classificationConfidence: 0.9,
          classificationSource: 'whisper_local' as const,
          fullTranscription: 'Original machine transcript generated by Whisper.',
          transcriptPath: txtPath,
          isExcluded: false,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
        };
        dedup.addVirtualClip(clipRecord);

        // 1. User edits transcript: should create .edited.txt and record versions
        const editedText = 'User corrected transcript with custom edits and names.';
        const updated = dedup.updateVirtualClip('clip_f10', {
          editedTranscript: editedText,
        });

        expect(updated).toBeDefined();
        expect(updated?.editedTranscript).toBe(editedText);

        const editedSidecar = path.join(rawDir, 'TAKE_F10.edited.txt');
        expect(fs.existsSync(editedSidecar)).toBe(true);
        expect(fs.readFileSync(editedSidecar, 'utf-8')).toBe(editedText);

        // Check version history
        expect(updated?.transcriptVersions).toBeDefined();
        expect(updated?.transcriptVersions?.length).toBeGreaterThanOrEqual(2);
        expect(updated?.transcriptVersions?.some((v) => v.source === 'machine')).toBe(true);
        expect(updated?.transcriptVersions?.some((v) => v.source === 'user_edit')).toBe(true);

        // 2. Revert edits: should remove .edited.txt sidecar
        const reverted = dedup.updateVirtualClip('clip_f10', {
          editedTranscript: '',
        });
        expect(reverted?.editedTranscript).toBe('');
        expect(fs.existsSync(editedSidecar)).toBe(false);
        // Original machine sidecar remains intact
        expect(fs.existsSync(txtPath)).toBe(true);
      } finally {
        try {
          fs.rmSync(sandboxVaultDir, { recursive: true, force: true });
        } catch {}
      }
    });

    it('preserves userTitle and editedTranscript during pipeline re-processing', async () => {
      const sandboxVaultDir = fs.mkdtempSync(path.join(os.tmpdir(), 'f10-orch-vault-'));
      const sandboxSrcDir = fs.mkdtempSync(path.join(os.tmpdir(), 'f10-orch-src-'));

      try {
        const testDedup = new DedupEngine(sandboxVaultDir);
        const testWatcher = new VolumeWatcher(testDedup);
        const testAudio = new AudioEngine();
        const testOrch = new PipelineOrchestrator(testDedup, testWatcher, testAudio);

        const file = path.join(sandboxSrcDir, 'PROTECTED_TAKE.WAV');
        fs.writeFileSync(file, generateSyntheticWavBuffer({ durationSeconds: 0.8, frequency: 440 }));

        testOrch.enqueueBatch([file], undefined, undefined, true);

        // Wait for initial ingest
        await new Promise<void>((resolve) => {
          testOrch.on('pipeline-status', (status) => {
            if (status.completedJobs >= 1) resolve();
          });
          setTimeout(resolve, 4000);
        });

        const initialClips = testDedup.getVirtualClips();
        expect(initialClips.length).toBe(1);
        const clip = initialClips[0];

        // User edits title and transcript
        testDedup.updateVirtualClip(clip.id, {
          title: 'My Custom Song Title',
          userTitle: 'My Custom Song Title',
          editedTranscript: 'Custom user lyrics for the verse.',
        });

        // Re-process the clip through orchestrator
        testOrch.reprocessClip(clip.id);

        // Wait for reprocess
        await new Promise<void>((resolve) => {
          testOrch.on('pipeline-status', (status) => {
            if (status.completedJobs >= 2) resolve();
          });
          setTimeout(resolve, 4000);
        });

        const reprocessedClip = testDedup.getVirtualClip(clip.id);
        expect(reprocessedClip).toBeDefined();
        // Title must remain user-owned
        expect(reprocessedClip?.title).toBe('My Custom Song Title');
        expect(reprocessedClip?.userTitle).toBe('My Custom Song Title');
        // Edited transcript must be preserved
        expect(reprocessedClip?.editedTranscript).toBe('Custom user lyrics for the verse.');
      } finally {
        try {
          fs.rmSync(sandboxVaultDir, { recursive: true, force: true });
          fs.rmSync(sandboxSrcDir, { recursive: true, force: true });
        } catch {}
      }
    });
  });
});
